version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - pip install -r docs/requirements.txt
    - cd docs && sphinx-build -b html -c . source $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false

formats:
  - htmlzip