version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - pip install -r docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
  builder: html
  fail_on_warning: false

formats:
  - htmlzip
  - pdf

# 多语言支持配置
builds:
  latest:
    configuration: docs/source/conf.py
    fail_on_warning: false
  zh_CN:
    configuration: docs/source/conf.py
    fail_on_warning: false
  en:
    configuration: docs/source/conf.py
    fail_on_warning: false